//
// Created by kneiv on 5/16/2022.
//

#ifndef STEGANOGRAPHY_PROJECT_BMPCOLORHEADER_H
#define STEGANOGRAPHY_PROJECT_BMPCOLORHEADER_H


class BMPColorHeader {

};


#endif //STEGANOGRAPHY_PROJECT_BMPCOLORHEADER_H
