//
// Created by kneiv on 5/17/2022.
//

#ifndef STEGANOGRAPHY_PROJECT_PNGFILEHEADER_H
#define STEGANOGRAPHY_PROJECT_PNGFILEHEADER_H


struct PNGFIleHeader {

};


#endif //STEGANOGRAPHY_PROJECT_PNGFILEHEADER_H
